;WITH e1(n) AS
(
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
), -- 10
e2(n) AS (SELECT 1 FROM e1 CROSS JOIN e1 AS b), -- 10*10
e3(n) AS (SELECT 1 FROM e1 CROSS JOIN e2 AS b), -- 10*100
e4(n) AS (SELECT 1 FROM e3 CROSS JOIN e3 AS b),  -- 1000*1000
numbers AS (SELECT number = ROW_NUMBER() OVER (ORDER BY n) FROM e4)
SELECT number
FROM (	SELECT TOP 10 number
		FROM numbers
		WHERE number < 1000
		ORDER BY NEWID() DESC 
	UNION
		SELECT TOP 10 number
		FROM numbers
		WHERE number < 1000
		ORDER BY NEWID() DESC 
	UNION
		SELECT TOP 10 number
		FROM numbers
		WHERE number < 1000
		ORDER BY NEWID() DESC  
	UNION
		SELECT TOP 10 number
		FROM numbers
		WHERE number < 1000
		ORDER BY NEWID() DESC 
	) AS TAB
    
